server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:3000/eureka/
  instance:
    instance-id: power-1 #此实例注册到eureka服务端得唯一得实例ID
    prefer-ip-address: true #是否显示ip地址
    lease-renewal-interval-in-seconds: 1 #心跳间隔
    lease-expiration-duration-in-seconds: 3 #超过30秒没有发送心跳，说明该节点已经宕机 默认为90秒
spring:
  application:
    name: server-power #客户端得名字
  zipkin:
    base-url: http://localhost:9000  #指定Zipkin server地址
  sleuth:
    sampler:
      probability: 1.0  #request采样的数量得标准 默认是0.1 也即是10% 顾名思义 采取10%的请求数据
      #因为在分布式系统中，数据量可能会非常大，因此采样非常重要。我们示例数据少最好配置为1全采样