server:
  port: 8080
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/heweidong1/kgc-cloud-config-test.git
          #     search-paths: foo,bar* #Configserver会在 Git仓库根目录、 foo子目录，以及所有以
          #bar开始的子目录中查找配置文件。
          #     clone-on-start: true #启动时就clone仓库到本地，默认是在配置被首次请求时，config
          #server才会clone git仓库
eureka:
  client:
    service-url:
      defaultZone: http://localhost:3000/eureka/
  instance:
    instance-id: config-0 #此实例注册到eureka服务端得唯一得实例ID
    prefer-ip-address: true #是否显示ip地址
    lease-renewal-interval-in-seconds: 1 #心跳间隔
    lease-expiration-duration-in-seconds: 3 #超过30秒没有发送心跳，说明该节点已经宕机 默认为90秒
