server:
  port: 3002
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000 #清理无效节点 ，清理宕机得服务
  instance:
    hostname: eureka3002


  client:
    #不把自己注册到eureka中
    registerWithEureka: false
    #不需要从服务端获取注册信息
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka3001.com:3001/eureka,http://eureka3000.com:3000/eureka
