server:
  port: 6000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:3000/eureka/
  instance:
    instance-id: power-0 #此实例注册到eureka服务端得唯一得实例ID
    prefer-ip-address: true #是否显示ip地址
    lease-renewal-interval-in-seconds: 1 #心跳间隔
    lease-expiration-duration-in-seconds: 3 #超过30秒没有发送心跳，说明该节点已经宕机 默认为90秒
spring:
  application:
    name: server-power #客户端得名字